name: "On PR"

on:
  pull_request:
    branches: [main, dev]

jobs:
  develop:
    name: "on_PR Dev"
    if: ${{ github.base_ref  == 'dev' }}
    uses: ./.github/workflows/pull_request.yml
    permissions:
      contents: read
      pull-requests: write
    secrets: inherit
    with:
        environment_name: dev

  prod:
    name: "on_PR Prod"
    if: ${{ github.base_ref == 'main' }}
    uses: ./.github/workflows/pull_request.yml
    permissions:
      contents: read
      pull-requests: write
    secrets: inherit
    with:
        environment_name: prod